#!/usr/bin/env python3
"""YouTube thumbnail production for the 12-episode walkthrough series.

Layout follows the approved Ep 5 mockup: an ImageGen background, three
translucent bars (series label / episode keyword / "Ep. N of 12"), and the
Guaardvark mascot on the left. Backgrounds are generated by the system's own
ImageGen feature via /api/batch-image; composition is local Pillow.

Usage:
  thumbnails.py sample [N]        composite one episode from an existing image
  thumbnails.py dispatch [N ...]  queue background batches (all eps by default)
  thumbnails.py composite [N ...] build thumbnails from generated backgrounds
  thumbnails.py status            show dispatched batch states

Outputs land in data/outputs/demos/thumbnails/ (DEMO_THUMBNAIL_OUT overrides).
"""

import argparse
import json
import os
import sys
import time
from pathlib import Path

import requests
from PIL import Image, ImageDraw, ImageFilter, ImageFont, ImageOps

API = os.environ.get("GUAARDVARK_API", "http://localhost:5000") + "/api/batch-image"
REPO = Path(__file__).resolve().parents[2]
ASSET_DIR = REPO / "data/demo_assets/thumbnails"
FONT_PATH = ASSET_DIR / "fonts/Inter-Variable.ttf"
MASCOT_SRC = Path(
    os.environ.get("DEMO_MASCOT", ASSET_DIR / "mascot.png")
).expanduser()
OUT_DIR = Path(
    os.environ.get("DEMO_THUMBNAIL_OUT", REPO / "data/outputs/demos/thumbnails")
).expanduser()
STATE_FILE = ASSET_DIR / "dispatch_state.json"

W, H = 1920, 1080

# Episode keyword (big title) + background prompt. Prompts describe a single
# warm-lit physical object metaphor, matching the approved lantern look; no
# text in the image — all text is composited.
EPISODES = {
    1: ("FULL TOUR", "cinematic photo of a powerful desktop computer tower with a softly glowing GPU on a wooden workbench in a dark cozy workshop, warm amber accent lighting, shallow depth of field, no text"),
    2: ("CHAT BRAIN", "cinematic macro photo of a glowing filament sculpture shaped like a brain inside a glass dome on a dark desk, three distinct strands of light, warm and cool tones, shallow depth of field, no text"),
    3: ("FILE DESKTOP", "cinematic photo of an antique wooden card catalog cabinet with one drawer open and warm light spilling out, index cards fanned, dark library background, shallow depth of field, no text"),
    4: ("SCREEN AGENT", "cinematic photo of an elegant robotic hand hovering over a glowing computer mouse on a dark desk, precise mechanical fingers, warm rim lighting, shallow depth of field, no text"),
    5: ("IMAGE GEN", "cinematic photo of a hand lighting an antique brass oil lantern with a lit match, warm flame glow against a carved stone wall, shallow depth of field, no text"),
    6: ("VIDEO GEN", "cinematic photo of a vintage film camera with light rays streaming through spinning film reels, dust motes in the beam, dark studio, warm highlights, shallow depth of field, no text"),
    7: ("VOICE CLONE", "cinematic photo of a studio condenser microphone in a shock mount with a glowing audio waveform reflected in dark glass behind it, warm and teal accents, shallow depth of field, no text"),
    8: ("MUSIC VIDEO", "cinematic photo of a vinyl record spinning on a turntable with colorful concert lighting and a hint of haze, needle on the groove, dark club background, shallow depth of field, no text"),
    9: ("FILM CREW", "cinematic photo of a director's clapperboard and canvas chair on a dim film set, practical tungsten lights glowing behind, haze in the air, shallow depth of field, no text"),
    10: ("VIDEO EDITOR", "cinematic photo of film strips laid on a glowing lightbox on an editing desk, a loupe resting on one frame, dark room, warm light from below, shallow depth of field, no text"),
    11: ("SELF-REPAIR", "cinematic macro photo of a mechanical pocket watch with its gears exposed, tiny screwdriver resting beside it on a watchmaker's bench, warm lamp light, shallow depth of field, no text"),
    12: ("COMMAND CENTER", "cinematic photo of a mission control style desk panel with toggle switches and one guarded red switch, soft indicator lights, dark room, warm key light, shallow depth of field, no text"),
    13: ("WHAT'S NEW", "cinematic photo of a heavy wooden front door standing slightly open with warm light spilling through the gap onto dark stone steps, brass handle catching the light, shallow depth of field, no text"),
    14: ("SYSTEM MAP", "cinematic photo of an antique star chart spread on a dark navigator's table, brass dividers resting on it, constellations picked out by a warm lamp, shallow depth of field, no text"),
    15: ("SELF-CODING", "cinematic photo of a mechanical typewriter with a sheet of paper mid-line and a small brass padlock resting beside the keys, warm desk lamp, dark study, shallow depth of field, no text"),
    16: ("MCP", "cinematic photo of a vintage telephone switchboard with braided patch cables plugged into glowing jacks, one cable held mid-air, warm tungsten light, dark room, shallow depth of field, no text"),
    17: ("SWARM", "cinematic macro photo of five brass clockwork bees on a dark workbench, one with its wings blurred in motion, warm rim light and soft haze, shallow depth of field, no text"),
}

SERIES_LABEL = "GUAARDVARK DEMO"
BAR_ALPHA = 150  # 0-255


def font(size, weight=800):
    f = ImageFont.truetype(str(FONT_PATH), size)
    f.set_variation_by_axes([min(size, 144), weight])
    return f


def tracked(draw, xy, text, fnt, tracking, fill, anchor_center=None):
    """Draw text with letterspacing; PIL has no native tracking."""
    widths = [draw.textlength(c, font=fnt) for c in text]
    total = sum(widths) + tracking * (len(text) - 1)
    if anchor_center:
        x = anchor_center[0] - total / 2
        y = anchor_center[1]
    else:
        x, y = xy
    for c, w in zip(text, widths):
        draw.text((x, y), c, font=fnt, fill=fill)
        x += w + tracking
    return total


def white_mascot():
    """White-fill variant: invert RGB of the production mascot, keep alpha."""
    img = Image.open(MASCOT_SRC).convert("RGBA")
    r, g, b, a = img.split()
    inverted = Image.merge("RGBA", (*ImageOps.invert(Image.merge("RGB", (r, g, b))).split(), a))
    return inverted


def fit_cover(img, w, h):
    return ImageOps.fit(img.convert("RGB"), (w, h), Image.LANCZOS)


def composite(bg_path, ep_num, out_path):
    keyword, _ = EPISODES[ep_num]
    canvas = fit_cover(Image.open(bg_path), W, H).convert("RGBA")

    bars = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    bdraw = ImageDraw.Draw(bars)
    top_bar = (0, 55, W, 150)
    title_bar = (0, 285, W, 470)
    bottom_bar = (0, 820, W, 965)
    for box in (top_bar, title_bar, bottom_bar):
        bdraw.rectangle(box, fill=(0, 0, 0, BAR_ALPHA))
    canvas = Image.alpha_composite(canvas, bars)

    draw = ImageDraw.Draw(canvas)

    # Top bar: series label, wide-tracked, centered
    f_top = font(56, 700)
    tracked(draw, None, SERIES_LABEL, f_top, 34, (255, 255, 255, 255),
            anchor_center=(W // 2, 55 + (95 - 56) // 2 - 4))

    # Mascot on the left, drop shadow, overlapping the title bar
    mascot = white_mascot()
    m_h = 620
    m_w = int(mascot.width * m_h / mascot.height)
    mascot = mascot.resize((m_w, m_h), Image.LANCZOS)
    shadow = Image.new("RGBA", mascot.size, (0, 0, 0, 0))
    shadow.paste((0, 0, 0, 160), mask=mascot.split()[3])
    shadow = shadow.filter(ImageFilter.GaussianBlur(12))
    mx, my = 60, 245
    canvas.alpha_composite(shadow, (mx + 10, my + 14))
    canvas.alpha_composite(mascot, (mx, my))

    # Title: episode keyword, auto-fit right of the mascot
    draw = ImageDraw.Draw(canvas)
    x_left, x_right = mx + m_w + 40, W - 60
    size = 170
    while size > 60:
        f_title = font(size, 800)
        if draw.textlength(keyword, font=f_title) <= x_right - x_left:
            break
        size -= 6
    cx = (x_left + x_right) / 2
    ty = (title_bar[1] + title_bar[3]) / 2
    draw.text((cx, ty), keyword, font=f_title, fill=(255, 255, 255, 255), anchor="mm")

    # Bottom bar: episode counter, right-aligned
    f_ep = font(96, 800)
    label = f"Ep. {ep_num} of 12" if ep_num <= 12 else f"Ep. {ep_num}"
    ew = draw.textlength(label, font=f_ep)
    ebox = draw.textbbox((0, 0), label, font=f_ep)
    ey = (bottom_bar[1] + bottom_bar[3]) / 2 - (ebox[3] - ebox[1]) / 2 - ebox[1]
    draw.text((W - 90 - ew, ey), label, font=f_ep, fill=(255, 255, 255, 255))

    out_path.parent.mkdir(parents=True, exist_ok=True)
    flat = canvas.convert("RGB")
    flat.save(out_path, "PNG")
    # YouTube caps custom thumbnails at 2MB; the JPEG sibling is the upload file.
    flat.save(out_path.with_suffix(".jpg"), "JPEG", quality=90, optimize=True)
    return out_path


def load_state():
    if STATE_FILE.exists():
        return json.loads(STATE_FILE.read_text())
    return {}


def save_state(state):
    STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
    STATE_FILE.write_text(json.dumps(state, indent=2))


def dispatch(episodes):
    state = load_state()
    for n in episodes:
        _, prompt = EPISODES[n]
        resp = requests.post(f"{API}/generate/prompts", json={
            "prompts": [prompt] * 3,
            "model": "zimage-turbo",
            "width": 1600,
            "height": 896,
        }, timeout=30)
        resp.raise_for_status()
        batch_id = resp.json()["data"]["batch_id"]
        state[str(n)] = {"batch_id": batch_id, "prompt": prompt}
        print(f"ep{n:02d}: batch {batch_id}")
    save_state(state)


def batch_status(batch_id):
    r = requests.get(f"{API}/status/{batch_id}", timeout=15)
    r.raise_for_status()
    return r.json()["data"]


def status():
    state = load_state()
    if not state:
        print("nothing dispatched")
        return
    for n, info in sorted(state.items(), key=lambda kv: int(kv[0])):
        try:
            d = batch_status(info["batch_id"])
            print(f"ep{int(n):02d}: {d.get('status')} "
                  f"{d.get('completed_images', '?')}/{d.get('total_images', '?')}")
        except Exception as e:
            print(f"ep{int(n):02d}: status error: {e}")


def find_batch_images(batch_id):
    d = batch_status(batch_id)
    out = []
    for img in d.get("images", []) or []:
        p = img.get("path") or img.get("file_path")
        if p and Path(p).exists():
            out.append(Path(p))
    if not out:
        out_dir = d.get("output_dir")
        for root in ([Path(out_dir)] if out_dir else []) + [REPO / "data/cache/batch_generation" / batch_id]:
            if root.exists():
                out = sorted(root.glob("images/*.png")) or sorted(root.glob("*.png"))
                if out:
                    break
    return out


def composite_eps(episodes):
    state = load_state()
    for n in episodes:
        info = state.get(str(n))
        if not info:
            print(f"ep{n:02d}: no dispatched batch, skipping")
            continue
        images = find_batch_images(info["batch_id"])
        if not images:
            print(f"ep{n:02d}: no finished images yet")
            continue
        out = composite(images[0], n, OUT_DIR / f"guaardvark-demo-episode-{n:02d}.png")
        print(f"ep{n:02d}: {out}  (picked 1 of {len(images)}; alternates in batch "
              f"{info['batch_id']})")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("command", choices=["sample", "dispatch", "composite", "status"])
    ap.add_argument("episodes", nargs="*", type=int)
    ap.add_argument("--bg", help="background image for 'sample'")
    args = ap.parse_args()

    eps = args.episodes or sorted(EPISODES)
    if args.command == "sample":
        n = eps[0] if args.episodes else 5
        if not args.bg:
            sys.exit("sample needs --bg <image>")
        out = composite(Path(args.bg), n, OUT_DIR / f"sample-ep{n:02d}.png")
        print(out)
    elif args.command == "dispatch":
        dispatch(eps)
    elif args.command == "composite":
        composite_eps(eps)
    elif args.command == "status":
        status()


if __name__ == "__main__":
    main()
