"""production fk cascades — A1

Drop and recreate the FK constraints on production tables so deletes propagate
sensibly:
  productions.project_id              → SET NULL  (project gone, production keeps state)
  production_shots.production_id      → CASCADE   (production gone, shots gone)
  production_shots.voice_subject_id   → SET NULL  (subject removed, shot keeps text)
  production_shot_subjects.shot_id    → CASCADE
  production_shot_subjects.subject_id → CASCADE
  swarm_messages.production_id        → CASCADE

Without these, deleting a Production left orphan shots, shot_subjects, and
swarm_messages — and on Postgres the FK constraint refused the delete entirely.

Revision ID: 4d70a1b2cad3
Revises: 4c59d33e3b3a
Create Date: 2026-05-07 19:00:00.000000
"""
from alembic import op
from sqlalchemy import inspect


revision = "4d70a1b2cad3"
down_revision = "4c59d33e3b3a"
branch_labels = None
depends_on = None


# (table, column, ref_table, ref_column, fk_name, ondelete)
NEW_FKS = [
    ("productions", "project_id", "projects", "id", "fk_production_project_id", "SET NULL"),
    ("production_shots", "production_id", "productions", "id", "fk_production_shot_production_id", "CASCADE"),
    ("production_shots", "voice_subject_id", "subjects", "id", "fk_production_shot_voice_subject_id", "SET NULL"),
    ("production_shot_subjects", "shot_id", "production_shots", "id", "fk_pss_shot_id", "CASCADE"),
    ("production_shot_subjects", "subject_id", "subjects", "id", "fk_pss_subject_id", "CASCADE"),
    ("swarm_messages", "production_id", "productions", "id", "fk_swarm_message_production_id", "CASCADE"),
]


def upgrade():
    insp = inspect(op.get_bind())
    # Drop existing FKs on each affected table — names are autogenerated by
    # the original migration so reflection is the safe way to find them.
    for table in {fk[0] for fk in NEW_FKS}:
        for fk in insp.get_foreign_keys(table):
            if fk["name"]:
                op.drop_constraint(fk["name"], table, type_="foreignkey")

    for table, col, ref_table, ref_col, fk_name, ondelete in NEW_FKS:
        op.create_foreign_key(
            fk_name, table, ref_table, [col], [ref_col], ondelete=ondelete,
        )


def downgrade():
    for table, _, _, _, fk_name, _ in NEW_FKS:
        try:
            op.drop_constraint(fk_name, table, type_="foreignkey")
        except Exception:
            pass

    # Best-effort restore — original constraints had no explicit name and no
    # ondelete clause.
    op.create_foreign_key(None, "productions", "projects", ["project_id"], ["id"])
    op.create_foreign_key(None, "production_shots", "productions", ["production_id"], ["id"])
    op.create_foreign_key(None, "production_shots", "subjects", ["voice_subject_id"], ["id"])
    op.create_foreign_key(None, "production_shot_subjects", "production_shots", ["shot_id"], ["id"])
    op.create_foreign_key(None, "production_shot_subjects", "subjects", ["subject_id"], ["id"])
    op.create_foreign_key(None, "swarm_messages", "productions", ["production_id"], ["id"])
